server:
  port: 8085
  servlet:
    context-path: '/ead-authuser/'

spring:
  application:
    name: ead-authuser-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-authuser
    username: virtus
    password: master
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
logging:
  level:
    com.ead: TRACE
    org.springframework.web: DEBUG

ead:
  api:
    url:
      course: 'http://ead-course-service/ead-course'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost